Make rocks toml file detection support symlinks and add toml-edit dep
nvim-neorocks/rocks-edit.nvim pull request #6
Opened 2024-09-05 21:03 UTC by simifalaye

Currently, the rocks toml file detection doesn't work if you are using a symlink (ex. from a dotfiles repo) and also the use of `vim.fn.expand("%")` will return the buffer path relative to the cwd meaning that the absolute path returned by the `rocks.api` function will most likely not match the path of the current buffer in most cases.

Another issue I saw is that rocks-edit.nvim uses toml-edit and is dependent on the `parse_spanned` function which wasn't introduced till version `0.4.0` (bug fixed in `0.4.1`). Though this is implicitly pulled in by rocks.nvim which is a dependency of rocks-edit, the version that is pulled in by rocks.nvim is an older version and so it doesn't have the `parse_spanned` function. We should maybe declare an explicit dependency for toml-edit since a newer version is need. Don't know if this is the best solution here but just wanted to highlight it here.

2024-09-05 21:16 UTC, simifalaye commented
@mrcjkb

2024-09-06 00:21 UTC, mrcjkb requested changes
Thanks 🙏 

looks good to me.

Could you please split this into two conventional commits with `fix:` prefixes? 
Otherwise they won't show up in the generated changelog.

2024-09-06 07:41 UTC, mrcjkb approved these changes

2024-09-06 07:43 UTC, merged

2024-09-06 07:46 UTC, mrcjkb commented
I'm travelling right now, so I can't upload the new rockspec.

@vhyrro could you please do that if you have time? 🙏

2024-09-10 04:56 UTC, mrcjkb commented
The new rockspec is uploaded.

2024-09-10 14:26 UTC, simifalaye commented
Thanks! Though, I'm not seeing the new toml-edit dependency for the luarocks package.

2024-09-10 16:31 UTC, mrcjkb commented
must have forgotten to pull the change 🤦‍♂️

2024-09-10 18:12 UTC, mrcjkb commented
Fixed.

2024-09-10 20:23 UTC, simifalaye commented
I guess one thing I didn't consider is now rocks-edit will have a dependency on cargo because of toml-edit. rocks.nvim is pulling in the binaries so it's not needed there?

2024-09-11 02:40 UTC, mrcjkb commented
That shouldn't be a problem. As long as you're not on an unsupported architecture, rocks.nvim will pull the pre-built rock for rocks-edit too.